name: Continuous Integration
on:
  push:
    branches:
      - main
      - 'EXP-**'
jobs:
  call-continuous-integration-reusable:
    uses: devops-i1/github-reusable-workflow/.github/workflows/ci.yml@main
    with:
      project_name: frontend-expense
      npm_install: false
    secrets: inherit
