name: Continuous Integration
on: [push]
jobs:
  call-continuous-integration-reusable:
    uses: devops-i1/github-reusable-workflow/.github/workflows/ci.yml@main
    with:
      project_name: frontend-expense
    secrets: inherit