name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: devops-i1/github-reusable-workflow/.github/workflows/release.yml@main
    with:
      project_name: frontend-expense
      npm_install: false
    secrets: inherit